# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(943, 790)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tab_view = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_view.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_view.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab_view.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tab_view.setElideMode(QtCore.Qt.ElideLeft)
        self.tab_view.setDocumentMode(False)
        self.tab_view.setTabsClosable(False)
        self.tab_view.setMovable(False)
        self.tab_view.setTabBarAutoHide(False)
        self.tab_view.setObjectName("tab_view")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout.setObjectName("formLayout")
        self.numberOfInboundTrucksLabel = QtWidgets.QLabel(self.tab_1)
        self.numberOfInboundTrucksLabel.setObjectName("numberOfInboundTrucksLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.numberOfInboundTrucksLabel)
        self.numberOfInboundTrucksSpinBox = QtWidgets.QSpinBox(self.tab_1)
        self.numberOfInboundTrucksSpinBox.setObjectName("numberOfInboundTrucksSpinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.numberOfInboundTrucksSpinBox)
        self.numberOfOutboundTrucksLabel = QtWidgets.QLabel(self.tab_1)
        self.numberOfOutboundTrucksLabel.setObjectName("numberOfOutboundTrucksLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.numberOfOutboundTrucksLabel)
        self.numberOfOutboundTrucksSpinBox = QtWidgets.QSpinBox(self.tab_1)
        self.numberOfOutboundTrucksSpinBox.setObjectName("numberOfOutboundTrucksSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.numberOfOutboundTrucksSpinBox)
        self.numberOfCompoundTrucksLabel = QtWidgets.QLabel(self.tab_1)
        self.numberOfCompoundTrucksLabel.setObjectName("numberOfCompoundTrucksLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.numberOfCompoundTrucksLabel)
        self.numberOfCompoundTrucksSpinBox = QtWidgets.QSpinBox(self.tab_1)
        self.numberOfCompoundTrucksSpinBox.setObjectName("numberOfCompoundTrucksSpinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.numberOfCompoundTrucksSpinBox)
        self.numberOfReceivingDoorsLabel = QtWidgets.QLabel(self.tab_1)
        self.numberOfReceivingDoorsLabel.setObjectName("numberOfReceivingDoorsLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.numberOfReceivingDoorsLabel)
        self.numberOfReceivingDoorsSpinBox = QtWidgets.QSpinBox(self.tab_1)
        self.numberOfReceivingDoorsSpinBox.setObjectName("numberOfReceivingDoorsSpinBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.numberOfReceivingDoorsSpinBox)
        self.numberOfShippingDoorsLabel = QtWidgets.QLabel(self.tab_1)
        self.numberOfShippingDoorsLabel.setObjectName("numberOfShippingDoorsLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.numberOfShippingDoorsLabel)
        self.numberOfShippingDoorsSpinBox = QtWidgets.QSpinBox(self.tab_1)
        self.numberOfShippingDoorsSpinBox.setObjectName("numberOfShippingDoorsSpinBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.numberOfShippingDoorsSpinBox)
        self.numberOfGoodsLabel = QtWidgets.QLabel(self.tab_1)
        self.numberOfGoodsLabel.setObjectName("numberOfGoodsLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.numberOfGoodsLabel)
        self.numberOfGoodsSpinBox = QtWidgets.QSpinBox(self.tab_1)
        self.numberOfGoodsSpinBox.setObjectName("numberOfGoodsSpinBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.numberOfGoodsSpinBox)
        self.loadingTumeLabel = QtWidgets.QLabel(self.tab_1)
        self.loadingTumeLabel.setObjectName("loadingTumeLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.loadingTumeLabel)
        self.loadingTumeLineEdit = QtWidgets.QLineEdit(self.tab_1)
        self.loadingTumeLineEdit.setObjectName("loadingTumeLineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.loadingTumeLineEdit)
        self.truckChangeoverTimeLabel = QtWidgets.QLabel(self.tab_1)
        self.truckChangeoverTimeLabel.setObjectName("truckChangeoverTimeLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.truckChangeoverTimeLabel)
        self.truckChangeoverTimeLineEdit = QtWidgets.QLineEdit(self.tab_1)
        self.truckChangeoverTimeLineEdit.setObjectName("truckChangeoverTimeLineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.truckChangeoverTimeLineEdit)
        self.effectOfTheArrivalTimesOnMakespanLabel = QtWidgets.QLabel(self.tab_1)
        self.effectOfTheArrivalTimesOnMakespanLabel.setObjectName("effectOfTheArrivalTimesOnMakespanLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.effectOfTheArrivalTimesOnMakespanLabel)
        self.effectOfTheArrivalTimesOnMakespanLineEdit = QtWidgets.QLineEdit(self.tab_1)
        self.effectOfTheArrivalTimesOnMakespanLineEdit.setObjectName("effectOfTheArrivalTimesOnMakespanLineEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.effectOfTheArrivalTimesOnMakespanLineEdit)
        self.truckTransferTimeLabel = QtWidgets.QLabel(self.tab_1)
        self.truckTransferTimeLabel.setObjectName("truckTransferTimeLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.truckTransferTimeLabel)
        self.truckTransferTimeLineEdit = QtWidgets.QLineEdit(self.tab_1)
        self.truckTransferTimeLineEdit.setObjectName("truckTransferTimeLineEdit")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.truckTransferTimeLineEdit)
        self.inboundArrivalTimeLabel = QtWidgets.QLabel(self.tab_1)
        self.inboundArrivalTimeLabel.setObjectName("inboundArrivalTimeLabel")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.inboundArrivalTimeLabel)
        self.inboundArrivalTimeLineEdit = QtWidgets.QLineEdit(self.tab_1)
        self.inboundArrivalTimeLineEdit.setObjectName("inboundArrivalTimeLineEdit")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.inboundArrivalTimeLineEdit)
        self.outboundArrivalTimeLabel = QtWidgets.QLabel(self.tab_1)
        self.outboundArrivalTimeLabel.setObjectName("outboundArrivalTimeLabel")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.outboundArrivalTimeLabel)
        self.outboundArrivalTimeLineEdit = QtWidgets.QLineEdit(self.tab_1)
        self.outboundArrivalTimeLineEdit.setObjectName("outboundArrivalTimeLineEdit")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.outboundArrivalTimeLineEdit)
        self.goodTransferTimeLabel = QtWidgets.QLabel(self.tab_1)
        self.goodTransferTimeLabel.setObjectName("goodTransferTimeLabel")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.goodTransferTimeLabel)
        self.goodTransferTimeLineEdit = QtWidgets.QLineEdit(self.tab_1)
        self.goodTransferTimeLineEdit.setObjectName("goodTransferTimeLineEdit")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.goodTransferTimeLineEdit)
        self.numberOfDataSetsLabel = QtWidgets.QLabel(self.tab_1)
        self.numberOfDataSetsLabel.setObjectName("numberOfDataSetsLabel")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.numberOfDataSetsLabel)
        self.numberOfDataSetsSpinBox = QtWidgets.QSpinBox(self.tab_1)
        self.numberOfDataSetsSpinBox.setMinimum(0)
        self.numberOfDataSetsSpinBox.setProperty("value", 0)
        self.numberOfDataSetsSpinBox.setObjectName("numberOfDataSetsSpinBox")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.numberOfDataSetsSpinBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.datasettable = QtWidgets.QTableView(self.tab_1)
        self.datasettable.setAccessibleDescription("")
        self.datasettable.setLineWidth(1)
        self.datasettable.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.datasettable.setTabKeyNavigation(False)
        self.datasettable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.datasettable.setSortingEnabled(True)
        self.datasettable.setObjectName("datasettable")
        self.datasettable.horizontalHeader().setCascadingSectionResizes(True)
        self.datasettable.horizontalHeader().setDefaultSectionSize(70)
        self.verticalLayout.addWidget(self.datasettable)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.inbound_good_table = QtWidgets.QTableView(self.tab_1)
        self.inbound_good_table.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.inbound_good_table.setObjectName("inbound_good_table")
        self.verticalLayout_2.addWidget(self.inbound_good_table)
        self.compound_coming_good_table = QtWidgets.QTableView(self.tab_1)
        self.compound_coming_good_table.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.compound_coming_good_table.setObjectName("compound_coming_good_table")
        self.verticalLayout_2.addWidget(self.compound_coming_good_table)
        self.outbound_good_table = QtWidgets.QTableView(self.tab_1)
        self.outbound_good_table.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.outbound_good_table.setObjectName("outbound_good_table")
        self.verticalLayout_2.addWidget(self.outbound_good_table)
        self.compound_going_good_table = QtWidgets.QTableView(self.tab_1)
        self.compound_going_good_table.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.compound_going_good_table.setObjectName("compound_going_good_table")
        self.verticalLayout_2.addWidget(self.compound_going_good_table)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 5)
        self.tab_view.addTab(self.tab_1, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.generate_times_button = QtWidgets.QPushButton(self.tab)
        self.generate_times_button.setObjectName("generate_times_button")
        self.gridLayout_2.addWidget(self.generate_times_button, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.arrival_time_table = QtWidgets.QTableView(self.tab)
        self.arrival_time_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.arrival_time_table.setObjectName("arrival_time_table")
        self.verticalLayout_3.addWidget(self.arrival_time_table)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.leaving_lower_table = QtWidgets.QTableView(self.tab)
        self.leaving_lower_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.leaving_lower_table.setObjectName("leaving_lower_table")
        self.verticalLayout_4.addWidget(self.leaving_lower_table)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.leaving_upper_table = QtWidgets.QTableView(self.tab)
        self.leaving_upper_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.leaving_upper_table.setObjectName("leaving_upper_table")
        self.verticalLayout_5.addWidget(self.leaving_upper_table)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 1, 2, 1, 1)
        self.print_gams = QtWidgets.QPushButton(self.tab)
        self.print_gams.setObjectName("print_gams")
        self.gridLayout_2.addWidget(self.print_gams, 0, 1, 1, 1)
        self.print_text = QtWidgets.QPushButton(self.tab)
        self.print_text.setObjectName("print_text")
        self.gridLayout_2.addWidget(self.print_text, 0, 2, 1, 1)
        self.tab_view.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.coming_sequence_table = QtWidgets.QTableView(self.tab_2)
        self.coming_sequence_table.setObjectName("coming_sequence_table")
        self.verticalLayout_6.addWidget(self.coming_sequence_table)
        self.gridLayout_4.addLayout(self.verticalLayout_6, 1, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.going_sequence_table = QtWidgets.QTableView(self.tab_2)
        self.going_sequence_table.setObjectName("going_sequence_table")
        self.verticalLayout_7.addWidget(self.going_sequence_table)
        self.gridLayout_4.addLayout(self.verticalLayout_7, 1, 1, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.sequence_error_table = QtWidgets.QTableView(self.tab_2)
        self.sequence_error_table.setObjectName("sequence_error_table")
        self.verticalLayout_8.addWidget(self.sequence_error_table)
        self.gridLayout_4.addLayout(self.verticalLayout_8, 1, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.solverLabel = QtWidgets.QLabel(self.tab_2)
        self.solverLabel.setObjectName("solverLabel")
        self.horizontalLayout.addWidget(self.solverLabel)
        self.solverComboBox = QtWidgets.QComboBox(self.tab_2)
        self.solverComboBox.setObjectName("solverComboBox")
        self.solverComboBox.addItem("")
        self.solverComboBox.addItem("")
        self.horizontalLayout.addWidget(self.solverComboBox)
        self.numberOfIterationsLabel = QtWidgets.QLabel(self.tab_2)
        self.numberOfIterationsLabel.setObjectName("numberOfIterationsLabel")
        self.horizontalLayout.addWidget(self.numberOfIterationsLabel)
        self.numberOfIterationsLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.numberOfIterationsLineEdit.setObjectName("numberOfIterationsLineEdit")
        self.horizontalLayout.addWidget(self.numberOfIterationsLineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.solve_data_set_button = QtWidgets.QPushButton(self.tab_2)
        self.solve_data_set_button.setObjectName("solve_data_set_button")
        self.horizontalLayout.addWidget(self.solve_data_set_button)
        self.data_set_spin_box = QtWidgets.QSpinBox(self.tab_2)
        self.data_set_spin_box.setMinimum(1)
        self.data_set_spin_box.setProperty("value", 1)
        self.data_set_spin_box.setObjectName("data_set_spin_box")
        self.horizontalLayout.addWidget(self.data_set_spin_box)
        self.stop_data_set_solve_button = QtWidgets.QPushButton(self.tab_2)
        self.stop_data_set_solve_button.setObjectName("stop_data_set_solve_button")
        self.horizontalLayout.addWidget(self.stop_data_set_solve_button)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 3)
        self.tab_view.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame = QtWidgets.QFrame(self.tab_4)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.sequence_grid = QtWidgets.QGridLayout()
        self.sequence_grid.setObjectName("sequence_grid")
        self.gridLayout_6.addLayout(self.sequence_grid, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.solve_one_sequence_button = QtWidgets.QPushButton(self.tab_4)
        self.solve_one_sequence_button.setObjectName("solve_one_sequence_button")
        self.horizontalLayout_2.addWidget(self.solve_one_sequence_button)
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.time = QtWidgets.QLCDNumber(self.tab_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.time.setFont(font)
        self.time.setObjectName("time")
        self.horizontalLayout_2.addWidget(self.time)
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.time_constant = QtWidgets.QLineEdit(self.tab_4)
        self.time_constant.setObjectName("time_constant")
        self.horizontalLayout_2.addWidget(self.time_constant)
        self.pause_button = QtWidgets.QPushButton(self.tab_4)
        self.pause_button.setObjectName("pause_button")
        self.horizontalLayout_2.addWidget(self.pause_button)
        self.resume_button = QtWidgets.QPushButton(self.tab_4)
        self.resume_button.setObjectName("resume_button")
        self.horizontalLayout_2.addWidget(self.resume_button)
        self.stop_button = QtWidgets.QPushButton(self.tab_4)
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout_2.addWidget(self.stop_button)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.graphicsView = Simulator(self.tab_4)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_5.addWidget(self.graphicsView, 2, 0, 1, 1)
        self.gridLayout_5.setRowStretch(2, 3)
        self.tab_view.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tab_view.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tab_view, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 943, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Data = QtWidgets.QAction(MainWindow)
        self.actionNew_Data.setObjectName("actionNew_Data")
        self.actionLoad_Data = QtWidgets.QAction(MainWindow)
        self.actionLoad_Data.setObjectName("actionLoad_Data")
        self.actionSave_Data = QtWidgets.QAction(MainWindow)
        self.actionSave_Data.setObjectName("actionSave_Data")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionNew_Data)
        self.menuFile.addAction(self.actionLoad_Data)
        self.menuFile.addAction(self.actionSave_Data)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_view.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cross Docking Solver"))
        self.numberOfInboundTrucksLabel.setText(_translate("MainWindow", "Number of Inbound Trucks"))
        self.numberOfOutboundTrucksLabel.setText(_translate("MainWindow", "Number of Outbound Trucks"))
        self.numberOfCompoundTrucksLabel.setText(_translate("MainWindow", "Number of Compound Trucks"))
        self.numberOfReceivingDoorsLabel.setText(_translate("MainWindow", "Number of Receiving Doors"))
        self.numberOfShippingDoorsLabel.setText(_translate("MainWindow", "Number of Shipping Doors"))
        self.numberOfGoodsLabel.setText(_translate("MainWindow", "Number of Goods"))
        self.loadingTumeLabel.setText(_translate("MainWindow", "Loading Time"))
        self.truckChangeoverTimeLabel.setText(_translate("MainWindow", "Truck Changeover Time"))
        self.effectOfTheArrivalTimesOnMakespanLabel.setText(_translate("MainWindow", "Effect of the arrival times on makespan"))
        self.truckTransferTimeLabel.setText(_translate("MainWindow", "Truck Transfer Time"))
        self.inboundArrivalTimeLabel.setText(_translate("MainWindow", "Inbound Arrival Time"))
        self.outboundArrivalTimeLabel.setText(_translate("MainWindow", "Outbound Arrival Time"))
        self.goodTransferTimeLabel.setText(_translate("MainWindow", "Good Transfer Time"))
        self.numberOfDataSetsLabel.setText(_translate("MainWindow", "Number of Data Sets"))
        self.tab_view.setTabText(self.tab_view.indexOf(self.tab_1), _translate("MainWindow", "Data Set"))
        self.generate_times_button.setText(_translate("MainWindow", "Generate"))
        self.label.setText(_translate("MainWindow", "Arrival Times"))
        self.label_2.setText(_translate("MainWindow", "Leaving Times Lower Boundary"))
        self.label_3.setText(_translate("MainWindow", "lLeaving Times Upper  Boundary"))
        self.print_gams.setText(_translate("MainWindow", "Gams Output"))
        self.print_text.setText(_translate("MainWindow", "Text Output"))
        self.tab_view.setTabText(self.tab_view.indexOf(self.tab), _translate("MainWindow", "Generate Times"))
        self.label_4.setText(_translate("MainWindow", "Coming Truck Sequences"))
        self.label_5.setText(_translate("MainWindow", "Going Truck Sequences"))
        self.label_6.setText(_translate("MainWindow", "Erros"))
        self.solverLabel.setText(_translate("MainWindow", "Solver"))
        self.solverComboBox.setItemText(0, _translate("MainWindow", "annealing"))
        self.solverComboBox.setItemText(1, _translate("MainWindow", "tabu"))
        self.numberOfIterationsLabel.setText(_translate("MainWindow", "Number of Iterations"))
        self.solve_data_set_button.setText(_translate("MainWindow", "Solve Data Set"))
        self.stop_data_set_solve_button.setText(_translate("MainWindow", "Stop"))
        self.tab_view.setTabText(self.tab_view.indexOf(self.tab_2), _translate("MainWindow", "Solve Data Set"))
        self.solve_one_sequence_button.setText(_translate("MainWindow", "Solve"))
        self.label_8.setText(_translate("MainWindow", "Time"))
        self.label_12.setText(_translate("MainWindow", "One step time"))
        self.time_constant.setText(_translate("MainWindow", "0.1"))
        self.pause_button.setText(_translate("MainWindow", "Pause"))
        self.resume_button.setText(_translate("MainWindow", "Resume"))
        self.stop_button.setText(_translate("MainWindow", "Stop"))
        self.tab_view.setTabText(self.tab_view.indexOf(self.tab_4), _translate("MainWindow", "Solve One Sequence"))
        self.tab_view.setTabText(self.tab_view.indexOf(self.tab_3), _translate("MainWindow", "Show Results"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionNew_Data.setText(_translate("MainWindow", "New Data"))
        self.actionLoad_Data.setText(_translate("MainWindow", "Load Data"))
        self.actionSave_Data.setText(_translate("MainWindow", "Save Data"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

from src.simulator import Simulator
